name: Package Release

on: 
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit tests
      run: |
        npm install
        npm test
      env:
        CI: true
    - name: Acceptance tests
      run: docker-compose -f spec/acceptance/docker-compose.yml up --force-recreate --exit-code-from node
      
    - name: Publish
      run: |
        npm run build
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        npm publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}